-- ============================================================
-- secciones_admin: agrega 'proveedores' al vocabulario (092) — una
-- sección MÁS ANGOSTA que 'accesos_externos' (que además cubre
-- mandantes/puertos/agencias/trazadores/códigos/puntos_limpios) y que
-- 'sii' (que en la práctica hoy es 100% sobre empresas proveedoras,
-- pero conceptualmente es "conexión SII", no "gestión de proveedores").
--
-- Puramente aditiva: un admin puede tener 'proveedores' SIN tener
-- 'accesos_externos' ni 'sii', y así llegar solo al CRUD de empresas
-- proveedoras + su cuenta de panel propio + su conexión SII, sin ver
-- mandantes/puertos/agencias/trazadores. El backend (routes/accesos.js,
-- routes/admin.js) acepta 'proveedores' como alternativa OR en los
-- endpoints específicos de proveedores — no reemplaza ni retira nada de
-- lo que 'accesos_externos'/'sii' ya otorgaban.
--
-- Sin backfill: a diferencia del alta original de la columna (092, que
-- sí necesitó respaldar cuentas existentes para no quitarles nada), acá
-- NO hay ningún comportamiento previo que preservar — es una sección
-- nueva, nadie la tenía. Que empiece en 0 cuentas es lo correcto.
-- ============================================================

-- ---------- POR QUÉ ACÁ YA NO SE TOCA EL CHECK ----------
--
-- Esta migración hacía DROP + ADD del CHECK con el vocabulario congelado
-- al 097. Como `migrate.js` NO lleva registro y corre TODOS los .sql en
-- cada arranque, ese ADD se volvía a ejecutar siempre — con una lista que
-- envejece. El día que una cuenta recibía una sección posterior (`cobros`,
-- de la 100), este archivo la declaraba inválida y **el servidor no
-- arrancaba**: `check constraint ... is violated by some row`, en el
-- arranque, en producción, después de un cambio hecho desde el panel.
--
-- Estuvo latente desde la 100. Se destapó al agregar 'activos' (110).
--
-- LA REGLA: el vocabulario se declara en UN SOLO lugar, la migración más
-- nueva que lo amplía. Las anteriores no lo re-afirman. Hay un test que
-- lo verifica — test/migracionesSecciones.test.js.
--
-- Lo que esta migración aporta ('proveedores' como sección propia) sigue
-- vigente: vive en la lista de la migración más nueva y en
-- src/constants/seccionesAdmin.js.
